name: Main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: tapasmishraarc/ReusableGitHubWorkflows/.github/workflows/template.yml@main
    with:
      ci-enabled: true
      dotnet-version: 5.0.x
      project-path: src/DemoReusableTemplates.csproj
      tech-type: dotnet
        

