name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_dotnet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build project
        uses: tapasmishraarc/demo-action-composite/Build/build.yml@main
        with:
          dotnet-version: 5.0.x
          project-path: src/DemoReusableTemplates.csproj
